### PR TITLE
Add app title and install button in NavBar on scroll

### PR DESCRIPTION
**Pull request by ialimz**
This PR adds app title and install button in NavigationBar on scroll

### CODE REVIEW

**Comment by ialimz** [comment]
@emranovin 
Would you please review this PR?

**Review by aminra96 — APPROVED** [review]

**Comment by aminra96** [comment]
@emranovin can you please merge this?

**Comment by Rminsh** [comment]
@ialimz Some things that should be noticed:
1- Please change your branch from `main` to `dev`. There are a lot of changes since the last commit in `main` and may break some views.
2- macOS target has build issues and some changes about navigation title should be addressed ( some `#if os(iOS)` in code for separation can fix the problem)

Besides that, loved the work 💙👌🏻
Thanks

**Review by Rminsh — CHANGES_REQUESTED** [review]
@ialimz Some things that should be noticed:
1- Please change your branch from `main` to `dev`. There are a lot of changes since the last commit in `main` and may break some views.
2- macOS target has build issues and some changes about navigation title should be addressed ( some `#if os(iOS)` in code for separation can fix the problem)

Besides that, loved the work 💙👌🏻
Thanks

**Comment by ialimz** [comment]
@Rminsh,
Thanks for your notes. I'll apply the changes you noticed and request for review again.

It would be better to change the repository's main branch to 'dev'

**Review by Rminsh — APPROVED** [review]

**Pull request merged**
